JST.chordSelector = ''
+ '<form class="chord_selector">'
+ '<select name="chord_root">'
+ '<option value="C">C</option>'
+ '<option value="D">D</option>'
+ '<option value="E">E</option>'
+ '<option value="F">F</option>'
+ '<option value="G">G</option>'
+ '<option value="A">A</option>'
+ '<option value="B">B</option>'
+ '</select>'
+ '<select name="chord_accidental">'
+ '<option value="">&#9838;</option>'
+ '<option value="#">&#9839;</option>'
+ '<option value="b">&#9837;</option>'
+ '</select>'
+ '<select name="chord_quality">'
+ '<option value="" selected="">Major</option>'
+ '<option value="m">Minor</option>'
+ '<option value="dim">dim</option>'
+ '<option value="aug">aug</option>'
+ '<option value="sus">sus</option>'
+ '</select>'
+ '<button type="submit">+</button>'
+ '</form>';
