Template.JST.chordSelector = ''
+ '<select name="chord_root">'
+ '<option value="c">C</option>'
+ '<option value="d">D</option>'
+ '<option value="e">E</option>'
+ '<option value="f">F</option>'
+ '<option value="g">G</option>'
+ '<option value="a">A</option>'
+ '<option value="b">B</option>'
+ '</select>'
+ '<select name="chord_accidental">'
+ '<option value="">&#9838;</option>'
+ '<option value="#">&#9839;</option>'
+ '<option value="b">&#9837;</option>'
+ '</select>'
+ '<select name="chord_symbol">'
+ '<option selected="">Major</option>'
+ '<option>Minor</option>'
+ '<option>dim</option>'
+ '<option>aug</option>'
+ '<option>sus</option>'
+ '<option>6</option>'
+ '<option>7</option>'
+ '<option>maj7</option>'
+ '<option>9</option>'
+ '<option>add9</option>'
+ '<option>m6</option>'
+ '<option>m7</option>'
+ '<option>mmaj7</option>'
+ '<option>m9</option>'
+ '<option>11</option>'
+ '<option>7sus4</option>'
+ '<option>13</option>'
+ '<option>6add9</option>'
+ '<option>-5</option>'
+ '<option>7-5</option>'
+ '<option>7maj5</option>'
+ '<option>maj9</option>'
+ '</select>';
