JST.chordSelector = ''
+ '<form class="chord_selector">'
+ '<select name="chord_root">'
+ '<option value="C">C</option>'
+ '<option value="C#">C#</option>'
+ '<option value="D">D</option>'
+ '<option value="Eb">Eb</option>'
+ '<option value="E">E</option>'
+ '<option value="F">F</option>'
+ '<option value="F#">F#</option>'
+ '<option value="G">G</option>'
+ '<option value="G#">G#</option>'
+ '<option value="A">A</option>'
+ '<option value="Bb">Bb</option>'
+ '<option value="B">B</option>'
+ '</select>'
+ '<select name="chord_quality">'
+ '<option value="" selected="">Major</option>'
+ '<option value="m">Minor</option>'
+ '<option value="6">6</option>'
+ '<option value="m6">m6</option>'
+ '<option value="69">69</option>'
+ '<option value="7">7</option>'
+ '<option value="m7">m7</option>'
+ '<option value="maj7">maj7</option>'
+ '<option value="7b5">7b5</option>'
+ '<option value="7#5">7#5</option>'
+ '<option value="m7b5">m7b5</option>'
+ '</select>'
+ '<button type="submit">+</button>'
+ '</form>';
