JST.chordData = ''
+ '<h3><% this.chord %></h3>'
+ '<ul>'
+ '<li>Intervals: <% this.intervals %></li>'
+ '<li>Notes'
+ '<ul>'
+ '<% for(var note in this.notes) { %>'
+ '<li>'
    + '<% this.notes[note].note %>, '
    + '<% this.notes[note].freq %>hz, '
    + '<% this.notes[note].midiKey %>'
+ '</li>'
+ '<% } %>'
+ '</ul></li>'
+ '<li>Dominant: <% this.dominant %></li>'
+ '<li>Subdominant: <% this.subdominant %></li>'
+ '<li>Voicings'
+ '<ul>'
+ '<% for(var voicing in this.voicings) { %>'
+ '<li>'
    + '<% this.voicings[voicing] %>, '
+ '</li>'
+ '<% } %>'
+ '</ul></li>'
+ '</ul>'
